# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'STYLiSH' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for STYLiSH
  pod 'Kingfisher', '~> 5.0'
  # pod 'MJRefresh'
  pod 'CRRefresh'
pod 'Alamofire', '~> 5.0.0-beta.5 '
  pod 'IQKeyboardManager'
  pod 'SwiftLint'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare'
  pod 'KeychainAccess'
end
